set -ex
export NEAR_ENV=mainnet
#near call meta-pipeline.near set_votes '{"project_id":64,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":65,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":66,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":67,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":68,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":69,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":70,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":71,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":72,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":73,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":74,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":75,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":76,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":77,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":78,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":79,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":80,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":81,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":82,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":83,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":84,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":85,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":86,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":87,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":88,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":89,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":90,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":91,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":92,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":93,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":94,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":95,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":96,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":97,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":98,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":99,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":100,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":101,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":102,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":103,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":104,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":105,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":106,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":107,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":108,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":109,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":110,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":111,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":112,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":113,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
near call meta-pipeline.near set_votes '{"project_id":114,"total_votes":"0","total_votes_percentage_bp":0}' --useAccount pipeline-operator.near --depositYocto 1
